export const events2 = [
{
	name:"Computer Science Club",
	date: "March 6th",
	time: "3:00 - 4:30pm",
	description: "Eager to expand your knowledge outside the classroom? Need help on school or outside projects? Come join the Computer Science Club! We will be recruiting new members and will also answer any questions you may have!",
	shortDescription: "Eager to expand your knowledge outside the classroom? Need help on school or outside projects? Come join the Computer Science Club!",
	food: "Cookies",
	icon: "../../images/cookie.png",
	foodDescription: "We will be offering cookies and other delicious baked goods at our event!",
	location: "Ballroom in the William Pitt Union",
	comments: "No programming experience required. All are welcome!",
	imgWidth: 30,
	imgHeight: 30,
	lat: 40.443952,
	long: -79.954462,
	page: "Template",
	test: "cookie",
	attendance: 15,
	day: 6

},
{
	name:"Health and Fitness",
	date: "March 6th",
	time: "1:00 - 3:00pm",
	description: "We will be sharing with you different activities and trends that emphasize the fun part of leading an active, healthy lifestyle. We will also offer ways to improve your diet for a more happy, healthy lifestyle.",
	shortDescription: "We will be sharing with you different activities and adjustments to diet to help you lead a more healthy lifestyle. Please stop by!",
	food: "Coffee",
	icon: "../../images/coffee.png",
	foodDescription: "We will be offering coffee and other beverages at our event",
	location: "Trees Hall room 101",
	comments: "From 1 to 2, we will be giving a talk, and from 2 to 3, you can join us in the weight room to learn about different exercises. Note we will not be offering any food from 2-3.",
	imgWidth: 40,
	imgHeight: 40,
	lat: 40.444568,
	long: -79.965018,
	page: "Health",
	test: "coffee",
	attendance: 33,
	day: 6
},

{
	name:"Club Fundraiser",
	date: "March 6th",
	time: "2:00 - 4:00pm",
	description: "Come stop by and help support our cause!  We will be raising money for Breast Cancer Charities. We will be having several guest speakers. No sign ups required so please drop by!",
	shortDescription: "Come stop by and help support our cause!  We will be raising money for Breast Cancer Charities. We will be having several guest speakers. No sign ups required!",
	food: "Pizza",
	icon: "../../images/Pizza-icon.png",
	foodDescription: "We will be offering free Pizza at our event!",
	location: "Peterson Event Center",
	imgWidth: 40,
	imgHeight: 40,
	lat: 40.442891,
	long: -79.956739,
	page: "Template",
	test: "pizza",
	attendance: 43,
	day: 6,
},

{
	name:"Random Club Event",
	date: "March 6th",
	time: "9:00 - 11:00am",
	description: "Come join us to learn about our new club. We will particulary discuss what are club is, our goals, and how we plan to achieve those goals. We will also be recruiting new members!",
	shortDescription: "Come join us to learn about our new club. We will be discussing our club hopes to achieve in the coming years. We will also be recruiting new members!",
	food: "Bagels",
	icon: "../../images/bagel.png",
	foodDescription: "We will be offering bagels and other breakfast items!",
	location: "Cathedral of Learning",
	imgWidth: 40,
	imgHeight: 40,
	lat: 40.444504,
	long: -79.953166,
	page: "RandomClub",
	test: "bagels",
	attendance: 32,
	day: 6,
},
{
	name:"Fundraising Event",
	date: "March 6th",
	time: "6:00 - 8:00pm",
	description: "We raising money for various charities have host several competitions. If you're interested, please sign up on our website! Hope to see you soon!",
	shortDescription: "We raising money for various charities have host several competitions. If you're interested, please sign up on our website! Hope to see you soon!",
	food: "Pizza",
	icon: "../../images/Pizza-icon.png",
	foodDescription: "We will be offering free Pizza at our event!",
	location: "Peterson Event Center",
	imgWidth: 40,
	imgHeight: 40,
	lat: 40.443886,
	long: -79.961990,
	page: "Template",
	test: "pizza",
	attendance: 25,
	day: 6
},

{
	name:"Go Greek",
	date: "March 6th",
	time: "4:00 - 5:30pm",
	description: "Come stop by and help support our cause!  We will be raising money for Breast Cancer Charities. We will be having several guest speakers. No sign ups required so please drop by!",
	shortDescription: "Come stop by and help support our cause!  We will be raising money for Breast Cancer Charities. We will be having several guest speakers. No sign ups required!",
	food: "Sandwiches",
	icon: "../../images/Pizza-icon.png",
	foodDescription: "We will be offering free Pizza at our event!",
	location: "Fraternity housing",
	imgWidth: 40,
	imgHeight: 40,
	lat: 40.445486,
	long:  -79.960571,
	page: "Template",
	test: "sandwiches",
	attendance: 41,
	day: 6
},

]